services:
  - type: web
    name: minute-burger
    runtime: python
    repo: https://github.com/Celivannn/deployment.git
    plan: free
    region: singapore
    rootDir: .  # Changed from PIT-Minute-Burger to .
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn minuteburger.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DB_ENGINE
        value: "django.db.backends.mysql"
      - key: DB_NAME
        value: "railway"
      - key: DB_USER
        value: "root"
      - key: DB_PASSWORD
        value: "riDQCkLfXmGFLeLVWyaSRSnttOLHTBRJ"
      - key: DB_HOST
        value: "maglev.proxy.rlwy.net"
      - key: DB_PORT
        value: "46734"